'use client';

import { useState } from 'react';
import { ArrowDown, ArrowLeft, ArrowRight, ArrowUp, Award, Bell, BookOpen, Briefcase, Calendar, Camera, Check, ChevronDown, ChevronLeft, ChevronRight, ChevronUp, Circle, Clock, Cloud, Code2, Download, Eye, FileText, Flag, Globe, Heart, Home, Image, Layers, Lightbulb, Link, Lock, Mail, MapPin, Menu, MessageCircle, Mic, Moon, Music, Package, Phone, Play, Plus, Search, Send, Settings, Shield, ShoppingBag, Star, Sun, Target, Trash2, TrendingUp, Upload, User, Users, Video, Volume2, Wifi, X, Zap } from 'lucide-react';

const ICONS = { arrowdown: ArrowDown, arrowleft: ArrowLeft, arrowright: ArrowRight, arrowup: ArrowUp, award: Award, bell: Bell, book: BookOpen, briefcase: Briefcase, calendar: Calendar, camera: Camera, check: Check, chevrondown: ChevronDown, chevronleft: ChevronLeft, chevronright: ChevronRight, chevronup: ChevronUp, circle: Circle, clock: Clock, cloud: Cloud, code: Code2, download: Download, eye: Eye, file: FileText, flag: Flag, globe: Globe, heart: Heart, home: Home, image: Image, social: MessageCircle, layers: Layers, lightbulb: Lightbulb, link: Link, lock: Lock, mail: Mail, map: MapPin, menu: Menu, message: MessageCircle, mic: Mic, moon: Moon, music: Music, package: Package, phone: Phone, play: Play, plus: Plus, search: Search, send: Send, settings: Settings, shield: Shield, shopping: ShoppingBag, star: Star, sun: Sun, target: Target, trash: Trash2, trending: TrendingUp, upload: Upload, user: User, users: Users, video: Video, volume: Volume2, wifi: Wifi, x: X, zap: Zap };

export default function IconElement({ element, editable, onChange }) {
  const [query, setQuery] = useState('');
  const Icon = ICONS[element.content || 'star'] || Star;
  const names = Object.keys(ICONS).filter((name) => name.includes(query.trim().toLowerCase()));
  return <div className="sm-icon-element" style={{ width: '100%', height: '100%', display: 'grid', placeItems: 'center', position: 'relative' }}><Icon size={Math.min(element.width, element.height) * .65} color={element.style?.color || '#fff'} strokeWidth={1.8} />{editable && <div className="sm-icon-picker" onMouseDown={(event) => event.stopPropagation()} style={{ position: 'absolute', zIndex: 140, left: 0, top: 'calc(100% + 10px)', width: 292, padding: 10, borderRadius: 10, background: '#151422', border: '1px solid rgba(255,255,255,.13)', boxShadow: '0 14px 32px rgba(0,0,0,.35)' }}><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search 60+ icons…" style={{ width: '100%', marginBottom: 8, border: '1px solid rgba(255,255,255,.13)', borderRadius: 7, padding: '8px 9px', background: '#0d0c16', color: '#fff', fontSize: 12 }} /><div style={{ maxHeight: 185, overflowY: 'auto', display: 'grid', gridTemplateColumns: 'repeat(6,1fr)', gap: 5 }}>{names.map((name) => { const PickerIcon = ICONS[name]; return <button type="button" key={name} title={name} aria-label={`Use ${name} icon`} onClick={() => onChange(name)} style={{ height: 37, display: 'grid', placeItems: 'center', border: element.content === name ? '1px solid #a78bfa' : '1px solid transparent', borderRadius: 7, background: element.content === name ? 'rgba(167,139,250,.2)' : 'rgba(255,255,255,.055)', color: '#e9e4ff', cursor: 'pointer' }}><PickerIcon size={17} /></button>; })}</div>{!names.length && <div style={{ padding: 12, color: '#aaa6b9', fontSize: 12, textAlign: 'center' }}>No icons found</div>}<small style={{ display: 'block', marginTop: 8, color: '#9d96b6', fontSize: 10 }}>{names.length} icons · click one to use it</small></div>}</div>;
}
