'use client';

import ColorPicker from './ColorPicker';

const SHADOWS = { none: 'none', small: '0 2px 8px rgba(0,0,0,.18)', medium: '0 8px 24px rgba(0,0,0,.22)', large: '0 18px 40px rgba(0,0,0,.28)', xl: '0 28px 70px rgba(0,0,0,.35)' };
const FONTS = ['Inter', 'DM Sans', 'Space Grotesk', 'Syne', 'Playfair Display', 'Lora', 'DM Mono', 'Bebas Neue', 'Arial', 'Helvetica', 'Georgia', 'Verdana', 'Trebuchet MS', 'Times New Roman', 'Montserrat', 'Poppins', 'Roboto', 'Open Sans', 'Manrope', 'Outfit', 'Sora', 'Archivo Black', 'Caveat', 'Pacifico', 'Abril Fatface', 'Anton', 'Bitter', 'Cardo', 'Cinzel', 'Cormorant Garamond', 'Crimson Text', 'Dancing Script', 'Figtree', 'Fraunces', 'IBM Plex Sans', 'Instrument Serif', 'Josefin Sans', 'Karla', 'Libre Baskerville', 'Libre Franklin', 'Merriweather', 'Mona Sans', 'Mukta', 'Noto Sans', 'Nunito', 'Oswald', 'PT Sans', 'Plus Jakarta Sans', 'Quicksand', 'Raleway', 'Rubik', 'Source Sans 3', 'Spectral', 'Ubuntu', 'Urbanist', 'Work Sans'];
const panelCss = `.sm-style-panel{display:grid;gap:12px}.sm-two-col{display:grid;grid-template-columns:1fr 1fr;gap:8px}.sm-align-row{display:grid;grid-template-columns:repeat(4,1fr);gap:5px;padding:4px;background:#0c0c14;border:1px solid rgba(255,255,255,.08);border-radius:10px}.sm-align-row button{height:29px;border:0;border-radius:6px;background:transparent;color:#8e8da0;cursor:pointer}.sm-align-row button.active{background:rgba(167,139,250,.22);color:#ede9fe}.sm-color-picker,.sm-shape-fill{padding:11px;border:1px solid rgba(255,255,255,.08);border-radius:11px;background:linear-gradient(145deg,rgba(255,255,255,.035),rgba(255,255,255,.012))}.sm-color-picker{display:grid;gap:9px}.sm-color-picker>.sm-field-label,.sm-shape-fill>.sm-field-label{display:block;color:#c4b5fd;font:700 10px 'DM Mono',monospace;letter-spacing:.08em;text-transform:uppercase}.sm-swatch-row{display:flex;align-items:center;gap:5px;flex-wrap:wrap}.sm-swatch-row button{width:23px;height:23px;flex:0 0 23px;padding:0;border:2px solid transparent;border-radius:7px;cursor:pointer}.sm-swatch-row button.active{border-color:#fff;box-shadow:0 0 0 2px rgba(167,139,250,.55)}.sm-swatch-row input[type=color]{width:25px;height:25px;padding:0;border:0;border-radius:7px;background:none;cursor:pointer}.sm-hex-row{display:grid;grid-template-columns:25px 1fr;gap:8px;align-items:center}.sm-hex-row span{height:25px;border-radius:7px;border:1px solid rgba(255,255,255,.18)}.sm-hex-row input{height:31px!important;padding:6px 8px!important;font:500 12px 'DM Mono',monospace!important}.sm-gradient-preview{height:54px;margin:9px 0;border:1px solid rgba(255,255,255,.15);border-radius:9px;box-shadow:inset 0 1px 0 rgba(255,255,255,.18),0 7px 16px rgba(0,0,0,.16)}.sm-fill-type{grid-template-columns:repeat(3,1fr);margin-top:8px}.sm-shadow-row{display:grid;grid-template-columns:repeat(3,1fr);gap:6px}.sm-shadow-row button{border:1px solid rgba(255,255,255,.08);border-radius:7px;background:#0c0c14;color:#a8a7b6;padding:8px 4px;font-size:11px;cursor:pointer}.sm-shadow-row button:hover,.sm-shadow-row button.active{border-color:rgba(167,139,250,.65);background:rgba(167,139,250,.16);color:#f5f3ff}.sm-shadow-row button:last-child{grid-column:span 2}`;

function ShapeFillControls({ style, set, setMany }) {
  const type = style.gradientType || 'solid';
  const colors = style.gradientColors?.length === 2 ? style.gradientColors : [style.backgroundColor || '#a78bfa', '#60a5fa'];
  const setColor = (index, value) => set('gradientColors', colors.map((color, colorIndex) => colorIndex === index ? value : color));
  const background = type === 'linear' ? `linear-gradient(${style.gradientAngle ?? 135}deg, ${colors.join(', ')})` : type === 'radial' ? `radial-gradient(circle at center, ${colors.join(', ')})` : colors[0];
  return <div className="sm-shape-fill">
    <span className="sm-field-label">Shape fill</span>
    <div className="sm-choice sm-fill-type">{[['solid', 'Solid'], ['linear', 'Gradient'], ['radial', 'Radial']].map(([value, label]) => <button type="button" key={value} className={type === value ? 'active' : ''} onClick={() => set('gradientType', value)}>{label}</button>)}</div>
    <div className="sm-gradient-preview" style={{ background }} />
    {type === 'solid' ? <ColorPicker label="Fill color" value={colors[0]} onChange={(value) => setMany({ backgroundColor: value, gradientColors: [value, colors[1]] })} /> : <><ColorPicker label="Gradient color 1" value={colors[0]} onChange={(value) => setColor(0, value)} /><ColorPicker label="Gradient color 2" value={colors[1]} onChange={(value) => setColor(1, value)} />{type === 'linear' && <label className="sm-field-label">Direction: {style.gradientAngle ?? 135}°<input type="range" min="0" max="360" value={style.gradientAngle ?? 135} onChange={(event) => set('gradientAngle', Number(event.target.value))} /></label>}</>}
  </div>;
}

export default function StylePanel({ element, onChange }) {
  const style = element.style || {};
  const set = (key, value) => onChange({ ...style, [key]: value });
  const setMany = (patch) => onChange({ ...style, ...patch });
  return <><style>{panelCss}</style><div className="sm-style-panel">
    <label className="sm-field-label">Font family<select value={style.fontFamily || 'Inter'} onChange={(event) => set('fontFamily', event.target.value)}>{FONTS.map((font) => <option key={font}>{font}</option>)}</select></label>
    <div className="sm-two-col"><label className="sm-field-label">Size<input type="number" min="8" max="160" value={style.fontSize || 18} onChange={(event) => set('fontSize', Number(event.target.value))} /></label><label className="sm-field-label">Weight<select value={style.fontWeight || 400} onChange={(event) => set('fontWeight', Number(event.target.value))}>{[400,500,600,700].map((weight) => <option key={weight} value={weight}>{weight}</option>)}</select></label></div>
    <div className="sm-align-row">{['left', 'center', 'right', 'justify'].map((align) => <button type="button" key={align} className={(style.textAlign || 'left') === align ? 'active' : ''} onClick={() => set('textAlign', align)}>{align === 'left' ? '≡' : align === 'center' ? '☷' : align === 'right' ? '≡' : '☰'}</button>)}</div>
    <ColorPicker label="Text color" value={style.color || '#ffffff'} onChange={(value) => set('color', value)} />
    {element.type === 'shape' ? <ShapeFillControls style={style} set={set} setMany={setMany} /> : <ColorPicker label="Background" value={style.backgroundColor || 'transparent'} onChange={(value) => set('backgroundColor', value)} />}
    <div className="sm-two-col"><label className="sm-field-label">Border px<input type="number" min="0" max="20" value={style.borderWidth || 0} onChange={(event) => set('borderWidth', Number(event.target.value))} /></label><label className="sm-field-label">Border style<select value={style.borderStyle || 'none'} onChange={(event) => set('borderStyle', event.target.value)}><option>none</option><option>solid</option><option>dashed</option><option>dotted</option></select></label></div>
    <ColorPicker label="Border color" value={style.borderColor || '#ffffff'} onChange={(value) => set('borderColor', value)} />
    <label className="sm-field-label">Radius: {style.borderRadius || 0}px<input type="range" min="0" max="100" value={style.borderRadius || 0} onChange={(event) => set('borderRadius', Number(event.target.value))} /></label>
    <label className="sm-field-label">Opacity: {Math.round((style.opacity ?? 1) * 100)}%<input type="range" min="0" max="1" step=".05" value={style.opacity ?? 1} onChange={(event) => set('opacity', Number(event.target.value))} /></label>
    <span className="sm-field-label">Shadow</span>
    <div className="sm-shadow-row">{Object.entries(SHADOWS).map(([name, shadow]) => <button type="button" key={name} className={(style.boxShadow || 'none') === shadow ? 'active' : ''} style={{ boxShadow: shadow === 'none' ? 'inset 0 0 0 1px rgba(255,255,255,.15)' : shadow }} onClick={() => set('boxShadow', shadow)}>{name}</button>)}</div>
  </div></>;
}
